version: '3.8'

services:
  postgres-test:
    image: postgres:14
    container_name: datweaver-test-postgres
    environment:
      POSTGRES_DB: datweaver_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d datweaver_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_test_data: 